name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Log in to Github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        build-args: PACKAGE_VERSION=${{ github.sha }}
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
