name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Log in to Github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Trim the commit hash for usage as version string
      id: get-version
      run: echo "::set-output name=version::${{ github.sha }}" | cut -c 1-34

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        build-args: PACKAGE_VERSION=${{ steps.get-version.outputs.version }}
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
