name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Log in to Github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Trim the commit hash for usage as version string
      id: get-version
      run: echo "version=${{ github.sha }}" | cut -c 1-15 >> $GITHUB_OUTPUT

    - name: Build the Docker image locally
      uses: docker/build-push-action@v3
      with:
        build-args: PACKAGE_VERSION=${{ steps.get-version.outputs.version }}
        load: true
        tags: ${{ github.repository }}

    - name: Run tests
      run: docker run --rm --volume ${PWD}/tests:/opt --workdir /usr/local/bin --entrypoint /opt/test-suite.sh ${{ github.repository }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        build-args: PACKAGE_VERSION=${{ steps.get-version.outputs.version }}
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
